// Chat Manager
var currentChatId=null;
function initChat(){loadCurrentChat();setupEvents();updateUserInfo();}
function setupEvents(){var i=document.getElementById("chat-input"),s=document.getElementById("send-btn"),n=document.getElementById("new-chat-btn");if(s)s.onclick=sendMessage;if(i){i.onkeydown=function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage();}};i.oninput=function(){autoResize(i);};}if(n)n.onclick=createNewChat;}
function autoResize(t){t.style.height="auto";t.style.height=Math.min(t.scrollHeight,200)+"px";}
function updateUserInfo(){var u=getUser(),une=document.getElementById("user-name"),uae=document.getElementById("user-avatar");if(u&&une)une.textContent=u;if(u&&uae)uae.textContent=getUserInitials();var p=getPreferences(),an=document.getElementById("ai-name");if(an&&p.aiName)an.textContent=p.aiName;}
function loadCurrentChat(){var c=getCurrentChat();if(c){var ch=getChat(c);if(ch){currentChatId=c;renderMessages(ch.messages);return;}}showEmpty();}
function showEmpty(){var m=document.getElementById("chat-messages");if(m)m.innerHTML="<div class=chat-empty><div class=chat-empty-icon>🤖</div><h3>How can I help you today?</h3><p>I can help you with questions.</p></div>";renderChatHistory();}
function renderMessages(msgs){var m=document.getElementById("chat-messages");if(!m)return;if(!msgs||msgs.length===0){showEmpty();return;}m.innerHTML=msgs.map(function(x){return createMsgHTML(x);}).join("");scrollBottom();renderChatHistory();}
function createMsgHTML(m){var isU=m.role==="user",ts=m.timestamp?new Date(m.timestamp).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"";var cnt=isU?eHTML(m.content):parseMD(m.content);return "<div class=message "+m.role+"><div class=message-avatar "+(isU?"user":"ai")+">"+(isU?"👤":"🤖")+"</div><div class=message-content><div class=message-bubble>"+cnt+"</div><div class=message-meta><span>"+ts+"</span></div></div></div>";}
function eHTML(t){var d=document.createElement("div");d.textContent=t;return d.innerHTML;}
function parseMD(t){if(!t)return"";var h=eHTML(t);h=h.replace(/```(\w*)\n([\s\S]*?)```/g,"<pre><code>$2</code></pre>");h=h.replace(/`([^`]+)`/g,"<code>$1</code>");h=h.replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>");return h.replace(/\n/g,"<br>");}
async function sendMessage(){var i=document.getElementById("chat-input"),s=document.getElementById("send-btn");if(!i||!s)return;var c=i.value.trim();if(!c)return;i.value="";i.disabled=true;s.disabled=true;if(!currentChatId){var ch=createChat("New Chat");currentChatId=ch.id;setCurrentChat(ch.id);}addMessage(currentChatId,{role:"user",content:c});var ch=getChat(currentChatId);renderMessages(ch.messages);showLoading();try{var r=await sendToAI(c);addMessage(currentChatId,{role:"assistant",content:r});hideLoading();var uc=getChat(currentChatId);renderMessages(uc.messages);}catch(e){hideLoading();addMessage(currentChatId,{role:"assistant",content:"Sorry, I encountered an error."});var uc=getChat(currentChatId);renderMessages(uc.messages);}i.disabled=false;s.disabled=false;i.focus();}
async function sendToAI(q){var p=getPreferences();if(!p.apiKey)return getMR();try{var r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+p.apiKey},body:JSON.stringify({model:"llama-3.1-70b-versatile",messages:[{role:"user",content:q}],temperature:0.7,max_tokens:2048})});if(!r.ok)throw new Error("E");var d=await r.json();if(d.choices&&d.choices[0])return d.choices[0].message.content;throw new Error("I");}catch(e){return getMR();}}
function getMR(){var rs=["I am AmkyawDev AI! Configure your API key in Settings.","I am running in demo mode. Add an API key in Settings."];return rs[Math.floor(Math.random()*rs.length)];}
function showLoading(){var m=document.getElementById("chat-messages");if(m)m.insertAdjacentHTML("beforeend","<div class=message id=loading><div class=message-avatar ai>🤖</div><div class=message-content><div class=typing-indicator><span></span><span></span><span></span></div></div></div>");scrollBottom();}
function hideLoading(){var l=document.getElementById("loading");if(l)l.remove();}
function scrollBottom(){var m=document.getElementById("chat-messages");if(m)m.scrollTop=m.scrollHeight;}
function createNewChat(){currentChatId=null;clearCurrentChat();showEmpty();closeSidebar();}
function loadChat(id){currentChatId=id;setCurrentChat(id);var c=getChat(id);if(c)renderMessages(c.messages);closeSidebar();}
function deleteChatItem(id,e){e.stopPropagation();deleteChat(id);if(currentChatId===id)createNewChat();else renderChatHistory();}
function renderChatHistory(){var l=document.getElementById("chat-history-list");if(!l)return;var cs=getChats();if(cs.length===0){l.innerHTML="<li style=color:var(--text-secondary);font-size:13px;padding:8px>No conversations yet</li>";return;}l.innerHTML=cs.map(function(c){return "<li class=sidebar-link onclick=loadChat(\""+c.id+"\")><span>"+eHTML(c.title)+"</span><button class=\"btn btn-sm\" onclick=deleteChatItem(\""+c.id+"\",event)>✕</button></li>";}).join("");}
function closeSidebar(){var s=document.querySelector(".sidebar");var o=document.getElementById("sidebar-overlay");if(s)s.classList.remove("show");if(o)o.classList.remove("show");}
function toggleSidebar(){var s=document.querySelector(".sidebar");var o=document.getElementById("sidebar-overlay");if(s)s.classList.toggle("show");if(o)o.classList.toggle("show");}
